### ISSUE TITLE
how to use this with flutter web?

### ISSUE THREAD

**Issue by oonid** [google/chartjs.dart#42]
Hi,

I know there're already same questions #40 #20 
But I saw in [pub.dev](https://pub.dev/packages/chartjs) this package support Flutter Web.
I just want to clarify that the flag is correct.

thank you.

**Comment by kevmoo** [comment]
Hrm. In theory you could use it, but you'd need to have an HTML wrapper. This API uses the JS charts API that renders to Canvas (or SVG, I forget)
