### ISSUE TITLE
ChartJS 2.0 

### ISSUE THREAD

**Issue by mofirouz** [google/chartjs.dart#5]
Hiya,

Thanks for maintaining this. I was wondering if there are any plans to move to the ChartJS 2.0 now that it's released? It fixes a ton of bugs and adds some nice new features.

Kind regards,
Mo.

**Comment by derekperkins** [comment]
@kevmoo: I'm one of the Chart.js collaborators, so if you have any migration questions, @etimberg, @tannerlinsley, @nnnick or myself are happy to help.

**Comment by lejard-h** [comment]
I started to update to 2.0
https://github.com/google/chartjs.dart/pull/7

Any help is welcome :)

**Comment by kevmoo** [comment]
> @kevmoo: I'm one of the Chart.js collaborators, so if you have any migration questions, @etimberg, @tannerlinsley, @nnnick or myself are happy to help.

Thanks much, @derekperkins – The biggest help will be making sure the `td.s` file is up-to-date

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/chart.js/chart.js.d.ts
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/chartjs/chart.d.ts

...and maybe working to figure which one of these should be removed 😄

**Comment by kevmoo** [comment]
Closed with 841e60a2ea585dfb92f0cd13dbf800a6eec9195d
