### ISSUE TITLE
Missing Align in ChartLegendOptions

### ISSUE THREAD

**Issue by tomas-kucera** [google/chartjs.dart#51]
There are two attributes for positioning legend:
- position - implemented - sets whether the legend is top, bottom, left, right
- align - not implemented - sets the alignment of the legend - start, center, end

**Solution:** just add to the begging of class ChartLegendOptions:
```
external String /*'start'|'center'|'end'*/ get align;
external set align(String /*'start'|'center'|'end'*/ v);
```
and 
```
String align,
```
to the top of the external factory ChartLegendOptions at the bottom of the class.

**Comment by kevmoo** [comment]
PRs welcome!

**Comment by tomas-kucera** [comment]
I guess we can close this as it was completed.
