### ISSUE TITLE
Questions on porting

### ISSUE THREAD

**Issue by kornha** [google/chartjs.dart#57]
Hi, great work and thanks for the example!

I have a few questions on this port I cannot figure out, and I was hoping I might be able to ask here, for learning purposes.

How did you include the dependencies Chart.js uses natively?
Which Chart.js file does this correspond to?
`https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.js` I cannot locate this on the [Chart.js github page](https://github.com/chartjs/Chart.js). Is this generated somehow?

**Comment by kevmoo** [comment]
I don't know, honestly. We haven't really touched this package in a while.
