### ISSUE TITLE
Can we use this in a flutter-for-web app? 

### ISSUE THREAD

**Issue by Cory-FanDemand** [google/chartjs.dart#58]
Hi,
Can we use this in a flutter-for-web app? If so an example would be greatly appreciated.
Thanks!

**Comment by kevmoo** [comment]
Nope. This is an HTML-only solution

**Comment by Cory-FanDemand** [comment]
Not even in some kind of webview? Do you know if other javascript libraries like react or jointjs could be made to work inside flutter-for-web?  Is there some UI event handling mechanism that would block them?  For example a drag event that a javascript library normally handles  - would flutter block those drag events from being automatically sent down to the javascript?
